# Generated by Django 3.2.3 on 2021-06-01 11:09

import DBope.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginName', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=20)),
                ('user_stats', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('status', models.IntegerField()),
                ('descript', models.TextField()),
                ('modify', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to=DBope.models.Result.user_directory_path)),
                ('result', models.FileField(upload_to=DBope.models.Result.user_directory_path)),
                ('status', models.IntegerField()),
                ('modify', models.DateTimeField(auto_now=True)),
                ('prodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBope.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.IntegerField()),
                ('PayMethod', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('paytime', models.DateTimeField()),
                ('modify', models.DateTimeField(auto_now=True)),
                ('finnish_time', models.DateTimeField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=3)),
                ('custID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBope.custlogin')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modify', models.DateTimeField(auto_now=True)),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBope.order')),
                ('prodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBope.product')),
                ('resultID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBope.result')),
            ],
        ),
        migrations.CreateModel(
            name='CustInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_last_name', models.CharField(max_length=20)),
                ('customer_first_name', models.CharField(max_length=20)),
                ('phone', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.IntegerField()),
                ('register_time', models.DateTimeField(auto_now_add=True)),
                ('account', models.DecimalField(decimal_places=2, max_digits=3)),
                ('modify', models.DateTimeField(auto_now=True)),
                ('custID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBope.custlogin')),
            ],
        ),
        migrations.CreateModel(
            name='CustBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField()),
                ('sn', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('custID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBope.custlogin')),
            ],
        ),
    ]
